language: node_js
os:
  - linux
dist: xenial
node_js:
  - "node"
branches:
  only:
    - main
script: skip
before_deploy:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist/
  fqdn: me.xcc.tw
  strategy: git
  on:
    branch: main
